### ISSUE TITLE
Tabs have no focus state

### ISSUE THREAD

**Issue by amaury-hanser** [ash-rocks/ash-css#1]
Hello, 

First of all, it's a nice project, congrats!
I've started to look at your components and I have an issue with the way you've build your tabs.

[Tabs in the docs](https://ashcss.rocks/docs/components/tab#intro)

**Issue:**
There is no focus state. The label of the tab is highlighted when selected but not different if you are focusing it or not.  
It means that if you're navigating in the page with your keyboard, you don't know when you are focusing the tabs.

How would you feel about adding a focus state? 
Something like this maybe? 

```
.tabs>input:focus+label {
 border-bottom-style: dashed;
}
```

**Comment by skulls-dot-codes** [comment]
Thanks for the kind words and issue! Tabs are a little hard to make with only CSS and currently are not responsive. Tabs will get some love in v0.3.0+. For now I will add a focus state.

**Comment by skulls-dot-codes** [comment]
Fixed in 6c20591

**Comment by amaury-hanser** [comment]
Looks good!

Tabs are tricky, do you plan to add _aria attributes_ at some point?

**Comment by skulls-dot-codes** [comment]
Aria attributes can be added to the docs. They are in most of the places where they are needed, but I'll audit the whole docs and add where necessary.
